package fr.alten.test_back.helper;

import java.util.Date;

/**
 * Class representing a JWT token generated by JWT service
 */
public class JwtToken {
    /**
     * Token value.
     */
    private String value;
    /**
     * Token expiration date.
     */
    private Date expirationDate;

    public JwtToken(){}


    /**
     * Get token value.
     * @return Token value.
     */
    public String getValue() {
        return this.value;
    }

    /**
     * Get token value.
     * @param value Token value.
     * @return self
     */
    public JwtToken setValue(String value) {
        this.value = value;
        return this;
    }

    /**
     * Get token expiration date.
     * @return Token expiration date.
     */
    public Date getExpirationDate() {
        return this.expirationDate;
    }

    /**
     * Set token expiration date.
     * @param expirationDate New expirationDate.
     * @return self
     */
    public JwtToken setExpirationDate(Date expirationDate) {
        this.expirationDate = expirationDate;
        return this;
    }
}
