package fr.alten.test_back.helper;

import java.util.Date;

/**
 * Class representing a JWT token generated by JWT service.
 * @param value Token value.
 * @param expirationDate Token expiration date.
 */
public record JwtToken (String value, Date expirationDate) {

}
