security:
  jwt:
    # JWT security key
    secret-key: '3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b'
    # JWT expiration time (1h in milliseconds)
    expiration-time: 3600000


